development: &sandbox
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
  signature: <%= ENV["SIGNATURE"] %>
  sandbox: true

test:
  <<: *sandbox

production: &production
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
  signature: <%= ENV["SIGNATURE"] %>
  sandbox: false

 